AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 130

Gemspec/DevelopmentDependencies:
  Enabled: false
