AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
    - 'lib/pronto/biome.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/pronto/biome.rb'

Naming/MethodParameterName:
  AllowedNames:
    - op

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 130

Gemspec/DevelopmentDependencies:
  Enabled: false
